#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x metaprogrammer`
puts `gem build metaprogrammer.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
